### PR TITLE
correct a little mistake in `hfo_game.cpp`

### PR DESCRIPTION
**Pull request by kxxwz**

### CODE REVIEW

**Comment by mhauskn** [comment]
I believe the code is correct as-is. ball-prox-delta is the change in ball proximity - so a positive ball_prox_delta should mean the agent is getting closer to the ball and should result in a positive reward.

**Comment by kxxwz** [comment]
As defined in `hfo_game.cpp`:
https://github.com/mhauskn/dqn-hfo/blob/c7b0a73de07078e248015d44573d8dcadd6fb8d1/src/hfo_game.cpp#L157
`ball_prox_delta > 0` means the distance between the agent and the ball is increased and the reward should be negative, while `ball_prox_delta < 0` means the agent is getting closer to the ball and the reward should be positive. 
And you can also refer to:
https://github.com/mhauskn/dqn-hfo/blob/c7b0a73de07078e248015d44573d8dcadd6fb8d1/src/hfo_game.cpp#L205
where `ball_dist_goal_delta` is similar to `ball_prox_delta`.
So I think I'm right.

**Comment by mhauskn** [comment]
Sorry for the confusing variable names:
ball_proximity is a feature that approaches 1 as the agent gets closer to the ball.

So if old_ball_prox = 0.5 and ball_proximity = 1.0, then the agent has moved toward the ball and ball_prox_delta will equal 0.5, which should correspond to a positive reward. Right?

**Comment by kxxwz** [comment]
Yes, you are right. I misunderstood the meaning of **proximity**. I appreciate your reply.

**Pull request closed without merging**
