### PR TITLE
Fix state size & hardcoded folder names

### PR DESCRIPTION
**Pull request by wbwatkinson**
This pull request attempts to resolve two issues:

First, it allows dqn-hfo to work with the current version of HFO by removing the last state feature before the comparison with DQN state features. See the chances to src/dqn_main.cpp. This is essentially a hack to keep dqn-hfo working with the current version of HFO. It does not incorporate the additional state variables into the analysis.

Second, it removes the hardcoded folder names from the hfo_policies files. CMake replaces the directory placeholder with the directory name and stores edited files in the build folder before compiling.

### CODE REVIEW

**Comment by mhauskn** [comment]
Thanks for the PR. For the 59th state feature why don't we just change the number of features that DQN is expecting to 59:

https://github.com/mhauskn/dqn-hfo/blob/master/src/hfo_game.hpp#L14

**Comment by wbwatkinson** [comment]
I tried modifying that line, but I had a blob dimension conflict later in the checks:
`dqn.cpp:44] Check failed: std::equal(blob_shape.begin(), blob_shape.end(), expected_shape.begin()) Blob "states" failed dimension check.`

I didn't chase that down...

**Comment by mhauskn** [comment]
This shouldn't be a problem. I suspect the code was trying to automatically
reload a previously saved network that had a state_size_ of 58. Please
clear all saved networks and try a fresh run.

**Comment by wbwatkinson** [comment]
You are correct. I can fix the PR. So the line should read:
`return 50 + 9 * (num_players);`

It looks like teammates and opponents also carry a uniform number, so I wasn't sure that `51 + 8 * (num_players);` is correct.

**Comment by wbwatkinson** [comment]
This should be ready. If merged, recommend closing [Issue #25](https://github.com/mhauskn/dqn-hfo/issues/25)

**Pull request merged**
