### PR TITLE
finish in mimic training function

### PR DESCRIPTION
**Pull request by yilunc2020**
When I run the program, I meet this compiling error and I don't know how to solve it.
image

### CODE REVIEW

**Comment by mhauskn** [comment]
So this error typically happens if the GPU on eldar-1 is already in use. You can run 'htop' to see the list of other processes and users. Sometimes other people test their code on eldar-1 so this is likely whats going on. When this happens it's a bit of a hassle, but you can just submit a job to the cluster so that it will get allocated to another gpu machine. The syntax for that is something like:

cluster -gpu -outfile job.out dqn-hfo [options]

**Comment by yilunc2020** [comment]
I have tried several runs with the command above. But every time the program aborts with the same error. Where can I see if other's are using the GPU right now?
image
Also are there any useful commands for the cluster I can submit, check status, track my job?

**Comment by yilunc2020** [comment]
I can't really remember the list of condor commands you told me a few months ago. Can you make a list of them? Or where can I find the documentation to check?

**Comment by mhauskn** [comment]
Sorry, I forgot to mention that you need to do the cluster command from a
submit node.

Try to ssh to submit64.cs.utexas.edu and submit the job from there.

Cluster script supports some commands: cluster-ls (list jobs), cluster-rm
(remove jobs)

It's just basically calling the native commands found below:

https://www.cs.utexas.edu/facilities/documentation/condor

**Pull request merged**
